# vader_custom_lexicon.py

"""
Custom sentiment terms for VADER.
Import `custom_words` from this module and call
`vader.lexicon.update(custom_words)` in your script.
Remember -- add "from vader_custom_lexicon import custom_words" to your
run_ script
"""

custom_words = {
    # ─── General market tone ─────────────────────────────────────────────
    "bullish": 3.2,
    "bearish": -3.2,
    "rally": 2.4,
    "selloff": -2.6,
    "soar": 3.0,
    "plummet": -3.0,
    "skyrocket": 3.5,
    "tank": -2.8,
    "breakout": 2.6,
    "breakdown": -2.6,
    "recovery": 2.3,
    "capitulation": -3.3,
    "moon": 3.8,
    "moonshot": 3.5,
    "dip": -0.7,
    "buy_the_dip": 2.5,
    "crash": -3.2,
    "correction": -1.2,
    "bubble": -2.4,
    "dead_cat_bounce": -2.5,
    "all_time_high": 3.6,
    "all_time_low": -3.6,
    "bull_run": 3.4,
    "market_meltdown": -3.8,
    "flash_crash": -3.5,
    "volatility_spike": -1.5,
    "risk_on": 1.4,
    "risk_off": -1.4,
    "safe_haven": 1.1,
    # ─── Trader slang / emotions ────────────────────────────────────────
    "fomo": -0.8,
    "bagholder": -2.0,
    "whale": 1.0,
    "hodl": 2.1,
    "hodling": 2.0,
    "fear": -2.1,
    "greed": 1.8,
    "panic_sell": -3.0,
    "short_squeeze": 2.0,
    "pump": 1.8,
    "dump": -2.6,
    "pump_and_dump": -3.6,
    "rugpull": -3.5,
    # ─── Corporate / earnings language ───────────────────────────────────
    "earnings_beat": 2.4,
    "earnings_miss": -2.4,
    "guidance_raise": 2.2,
    "guidance_cut": -2.2,
    "profit_take": 1.5,
    "profit_warning": -2.6,
    "dividend_hike": 2.3,
    "dividend_cut": -2.3,
    "share_buyback": 1.8,
    "share_dilution": -1.8,
    "upgrade": 2.1,
    "downgrade": -2.1,
    "rating_boost": 1.8,
    "rating_cut": -1.8,
    # ─── Macro & policy terms ───────────────────────────────────────────
    "quantitative_easing": 0.5,
    "quantitative_tightening": -1.2,
    "interest_rate_hike": -1.3,
    "interest_rate_cut": 1.3,
    "inflation_surge": -2.4,
    "deflation": -1.0,
    "stagflation": -3.0,
    "recession": -3.4,
    "depression": -3.8,
    "soft_landing": 1.5,
    "hard_landing": -2.5,
    "economic_expansion": 2.4,
    "stimulus": 1.2,
    "credit_crunch": -3.1,
    "yield_curve_inversion": -2.7,
    # ─── Balance-sheet / distress ───────────────────────────────────────
    "default": -3.5,
    "bankruptcy": -4.0,
    "chapter_11": -3.6,
    "insolvency": -3.6,
    "liquidation": -3.0,
    "margin_call": -2.8,
    "asset_write_down": -2.5,
    "leverage_buyout": 0.2,
    # ─── Crypto-specific positive ───────────────────────────────────────
    "halving": 1.4,
    "hashrate_record": 2.3,
    "mainnet_launch": 2.5,
    "whitepaper_release": 1.6,
    "etf_approval": 2.8,
    "token_listed": 2.0,
    "layer2_scaling": 1.1,
    "gas_fee_drop": 1.7,
    "airdrop": 1.3,
    "alt_season": 2.0,
    "nft_boom": 1.9,
    "metaverse_boost": 2.0,
    "token_burn": 1.5,
    "yield_farming": 1.2,
    "liquidity_mining": 1.0,
    "stablecoin_recovery": 2.1,
    # ─── Crypto-specific negative ───────────────────────────────────────
    "crypto_winter": -3.3,
    "depeg": -3.1,
    "hack": -3.4,
    "exploit": -2.8,
    "bridge_exploit": -3.2,
    "smart_contract_bug": -2.5,
    "exit_scam": -4.0,
    "treasury_drain": -2.7,
    "gas_fee_spike": -1.7,
    "testnet_delay": -1.4,
    "token_delisted": -2.0,
    "pow_ban": -2.3,
    "regulatory_crackdown": -2.2,
    "etf_rejection": -2.8,
    "cease_and_desist": -2.8,
    "fraudulent": -4.0,
    "securities_violation": -3.0,
    "class_action": -2.9,
    "hard_fork": -0.2,
    "fork": 0.0,
    "soft_fork": 0.2,
    "ordinals_collapse": -1.5,
    "nft_crash": -1.9,
    "impermanent_loss": -1.6,
    "validator_slash": -2.0,
    # ─── Neutral / mild, but useful context ─────────────────────────────
    "contango": 0.1,
    "backwardation": -0.1,
    "open_interest_surge": 0.9,
    "funding_rate_flip": 0.3,
    "market_depth": 0.4,
    "thin_liquidity": -1.1,
    "governance_vote": 0.5,
    "license_grant": 2.2,
    "settlement_reached": 1.0,
    "bailout": -0.8,
    "flight_to_quality": 0.7,
    "esg_compliance": 1.0,
    # ── market / price action ──
    "onboarding": -0.4,         # onboarding paused → mildly negative :contentReference[oaicite:0]{index=0}
    "offboarded": -2.0,         # lost banking access → negative :contentReference[oaicite:1]{index=1}
    "listing": 1.5,             # exchange listing → positive :contentReference[oaicite:2]{index=2}
    "delisting": -1.5,
    "gainer": 2.2,              # top daily gainer :contentReference[oaicite:3]{index=3}
    "resistance": -0.8,         # price stuck below resistance :contentReference[oaicite:4]{index=4}
    "support_level": 0.8,
    "leg_up": 1.3,
    "momentum": 1.4,            # “building momentum” :contentReference[oaicite:5]{index=5}
    "turbulence": -1.5,
    "liquidations": -1.9,       # large liquidations :contentReference[oaicite:6]{index=6}
    "retrace": -0.5,
    "retest": 0.6,
    "parabolic": 3.0,
    "melt_up": 2.8,
    "freefall": -3.0,
    "oversold": 1.0,
    "overbought": -1.1,
    "grind_higher": 1.3,
    "slump": -2.0,
    "bounce": 1.3,
    "headwinds": -1.2,
    "tailwinds": 1.2,
    # ── trader / crypto slang ──
    "ape_in": 1.6,
    "diamond_hands": 2.4,
    "paper_hands": -1.8,
    "rekt": -3.2,
    "degen": -1.0,
    "flippening": 1.7,
    # ── risk & attack vectors ──
    "front_run": -2.2,
    "sandwich_attack": -2.6,
    "oracle_failure": -2.9,
    "slashing": -2.0,
    "unstake": -0.6,
    # ── DeFi / staking ──
    "staking_reward": 1.7,
    "overleveraged": -2.3,
    "hashwar": -2.5,
    "ghost_chain": -2.4,
    # ── corporate / deal flow ──
    "pivot": 0.7,
    "windfall": 3.0,
    "oversubscribed": 2.0,
    "shortfall": -2.1,
    # ── macro / policy ──
    "hawkish": -0.9,
    "dovish": 0.9,
    "taper": -0.7,
    "fiscal_cliff": -2.5,
    # ── compliance / regulation ──
    "whitelist": 1.2,
    "blacklist": -1.2,
    # ── gas & fees ──
    "gasless": 1.5,
    "peg_restore": 2.0,
    
    # ─── Additional crypto-specific terms (100 new words) ───────────────
    # ── Technical indicators & patterns ──
    "golden_cross": 2.8,
    "death_cross": -2.8,
    "cup_and_handle": 2.2,
    "head_and_shoulders": -2.2,
    "ascending_triangle": 2.0,
    "descending_triangle": -2.0,
    "double_bottom": 2.1,
    "double_top": -2.1,
    "consolidation": 0.5,
    "accumulation": 1.8,
    "distribution": -1.8,
    
    # ── DeFi specific ──
    "total_value_locked": 1.6,
    "yield_boost": 2.0,
    "protocol_revenue": 1.7,
    "protocol_drain": -3.2,
    "reentrancy_attack": -3.4,
    "flash_loan_attack": -3.3,
    "liquidity_crisis": -3.0,
    "liquidity_injection": 2.5,
    "pool_drained": -3.5,
    "pool_replenished": 2.3,
    "farming_rewards": 1.8,
    "vesting_unlock": -1.2,
    "cliff_unlock": -1.5,
    "token_lockup": 1.3,
    "bonding_curve": 0.8,
    
    # ── Network & blockchain ──
    "network_congestion": -1.6,
    "throughput_increase": 2.0,
    "finality_achieved": 1.4,
    "chain_halt": -3.7,
    "chain_resume": 2.5,
    "consensus_failure": -3.5,
    "node_outage": -2.3,
    "validator_jailed": -2.2,
    "block_production": 0.6,
    "reorg": -2.6,
    "chain_split": -2.8,
    "merge_successful": 2.7,
    "upgrade_complete": 2.2,
    "upgrade_failed": -3.0,
    
    # ── Institutional & adoption ──
    "institutional_adoption": 3.2,
    "institutional_exit": -2.8,
    "treasury_purchase": 2.6,
    "treasury_sale": -2.4,
    "corporate_integration": 2.8,
    "partnership_dissolution": -2.3,
    "strategic_acquisition": 2.4,
    "hostile_takeover": -1.8,
    "venture_funding": 2.5,
    "funding_pulled": -3.0,
    "unicorn_valuation": 3.0,
    "down_round": -2.7,
    
    # ── Regulatory & compliance ──
    "regulatory_approval": 3.0,
    "regulatory_rejection": -3.0,
    "license_revoked": -3.3,
    "compliance_achieved": 2.4,
    "non_compliant": -2.6,
    "kyc_mandatory": -0.8,
    "sanctions": -3.5,
    "enforcement_action": -3.2,
    "regulatory_clarity": 2.6,
    "regulatory_uncertainty": -2.0,
    "tax_haven": 1.2,
    "tax_evasion": -3.4,
    
    # ── Security & risks ──
    "vulnerability_discovered": -2.8,
    "vulnerability_patched": 2.2,
    "audit_passed": 2.6,
    "audit_failed": -3.1,
    "penetration_test": 1.4,
    "security_breach": -3.6,
    "funds_recovered": 2.8,
    "funds_frozen": -2.5,
    "wallet_compromised": -3.4,
    "private_key_leaked": -4.0,
    "multisig_failure": -3.2,
    "timelock_expired": -1.0,
    
    # ── Mining & staking ──
    "difficulty_adjustment": 0.3,
    "mining_profitable": 2.2,
    "mining_unprofitable": -2.2,
    "pool_dominance": -1.5,
    "decentralization_increase": 2.0,
    "centralization_concern": -2.3,
    "stake_centralization": -2.4,
    "slashing_event": -2.7,
    "validator_set_expansion": 1.6,
    
    # ── Market sentiment ──
    "accumulation_phase": 2.3,
    "distribution_phase": -2.3,
    "smart_money": 2.1,
    "dumb_money": -1.9,
    "retail_euphoria": -1.7,
    "capitulation_bottom": 1.5,
    "max_pain": -2.2,
    "short_covering": 2.0,
    "long_liquidation": -2.5,
    "funding_negative": 1.3,
    "funding_positive": -0.8,
    
    # ── Project development ──
    "roadmap_achieved": 2.8,
    "roadmap_delayed": -2.4,
    "milestone_reached": 2.5,
    "development_stalled": -2.7,
    "community_growth": 2.2,
    "community_exodus": -2.8,
    "developer_activity": 1.9,
    "ghost_project": -3.3,
    "abandoned_project": -3.8,
    "revival": 2.6,
    "relaunch": 1.8,
    "rebrand": 0.6
}